import { Injectable } from '@nestjs/common';
import { PassThrough } from 'node:stream';
import PDFDocument from 'pdfkit';
import { BookRecord, ChapterRecord } from '../books/book.types';

interface TextSegment {
  text: string;
  bold: boolean;
  italic: boolean;
  code: boolean;
}

@Injectable()
export class ExportService {
  async exportBookToPdf(
    book: Pick<BookRecord, 'title'>,
    chapters: ChapterRecord[],
    finalReviewNotes?: string | null,
  ) {
    const doc = new PDFDocument({
      margin: 65,
      size: 'A4',
      info: {
        Title: book.title,
        Author: 'Automated Book Generator',
      },
    });

    const stream = new PassThrough();
    const chunks: Buffer[] = [];
    const pdfReady = new Promise<Buffer>((resolve, reject) => {
      stream.on('data', (chunk) =>
        chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)),
      );
      stream.on('end', () => resolve(Buffer.concat(chunks)));
      stream.on('error', reject);
      doc.on('error', reject);
    });

    doc.pipe(stream);

    // ── Title page ──────────────────────────────────────────────────────────
    doc
      .font('Helvetica-Bold')
      .fontSize(28)
      .fillColor('#111111')
      .text(book.title, { align: 'center' });

    doc.moveDown(0.5);
    doc
      .font('Helvetica')
      .fontSize(11)
      .fillColor('#888888')
      .text('Generated by Automated Book Generator', { align: 'center' });

    if (finalReviewNotes) {
      doc.moveDown(1.5);
      doc
        .font('Helvetica')
        .fontSize(11)
        .fillColor('#333333')
        .text(`Final review notes: ${finalReviewNotes}`);
    }

    // ── Chapters ─────────────────────────────────────────────────────────────
    for (const chapter of chapters) {
      doc.addPage();
      this.renderChapter(doc, chapter);
    }

    doc.end();
    return pdfReady;
  }

  // ── Chapter renderer ──────────────────────────────────────────────────────

  private renderChapter(doc: PDFKit.PDFDocument, chapter: ChapterRecord) {
    doc
      .font('Helvetica-Bold')
      .fontSize(20)
      .fillColor('#111111')
      .text(`Chapter ${chapter.chapterNumber}: ${chapter.title}`);

    doc.moveDown(0.8);

    if (chapter.content) {
      this.renderMarkdown(doc, chapter.content);
    } else {
      doc
        .font('Helvetica')
        .fontSize(12)
        .fillColor('#aaaaaa')
        .text('Chapter content not yet generated.');
    }

    if (chapter.summary) {
      doc.moveDown(1.2);
      doc
        .font('Helvetica-Oblique')
        .fontSize(10)
        .fillColor('#666666')
        .text(`Summary: ${chapter.summary}`);
    }
  }

  // ── Markdown → PDF ────────────────────────────────────────────────────────

  private renderMarkdown(doc: PDFKit.PDFDocument, markdown: string) {
    const lines = markdown.split('\n');
    let inCodeBlock = false;

    for (const line of lines) {
      // Toggle fenced code block
      if (line.trim().startsWith('```')) {
        inCodeBlock = !inCodeBlock;
        continue;
      }

      if (inCodeBlock) {
        doc
          .font('Courier')
          .fontSize(10)
          .fillColor('#333333')
          .text(line.length ? line : ' ', { lineGap: 1 });
        continue;
      }

      const trimmed = line.trim();

      // Blank line → paragraph spacing
      if (!trimmed) {
        doc.moveDown(0.4);
        continue;
      }

      // Headings
      if (trimmed.startsWith('#### ')) {
        doc.moveDown(0.3);
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#222222').text(trimmed.slice(5));
        doc.moveDown(0.15);
        continue;
      }
      if (trimmed.startsWith('### ')) {
        doc.moveDown(0.4);
        doc.font('Helvetica-Bold').fontSize(14).fillColor('#1a1a1a').text(trimmed.slice(4));
        doc.moveDown(0.2);
        continue;
      }
      if (trimmed.startsWith('## ')) {
        doc.moveDown(0.5);
        doc.font('Helvetica-Bold').fontSize(16).fillColor('#111111').text(trimmed.slice(3));
        doc.moveDown(0.25);
        continue;
      }
      if (trimmed.startsWith('# ')) {
        doc.moveDown(0.6);
        doc.font('Helvetica-Bold').fontSize(18).fillColor('#111111').text(trimmed.slice(2));
        doc.moveDown(0.3);
        continue;
      }

      // Horizontal rule
      if (/^[-*_]{3,}$/.test(trimmed)) {
        doc.moveDown(0.3);
        const y = doc.y;
        doc
          .moveTo(doc.page.margins.left, y)
          .lineTo(doc.page.width - doc.page.margins.right, y)
          .strokeColor('#cccccc')
          .stroke();
        doc.moveDown(0.3);
        continue;
      }

      // Bullet list
      if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        const content = trimmed.slice(2);
        this.renderInlineLine(
          doc,
          `• ${content}`,
          { indent: 12, lineGap: 2, paragraphGap: 2 },
        );
        continue;
      }

      // Numbered list (1. 2. etc.)
      if (/^\d+\.\s/.test(trimmed)) {
        this.renderInlineLine(doc, trimmed, { indent: 12, lineGap: 2, paragraphGap: 2 });
        continue;
      }

      // Blockquote
      if (trimmed.startsWith('> ')) {
        doc
          .font('Helvetica-Oblique')
          .fontSize(12)
          .fillColor('#555555')
          .text(trimmed.slice(2), { indent: 18, lineGap: 2 });
        continue;
      }

      // Normal paragraph
      this.renderInlineLine(doc, trimmed, { lineGap: 3, paragraphGap: 5 });
    }
  }

  // ── Inline formatter ──────────────────────────────────────────────────────

  private renderInlineLine(
    doc: PDFKit.PDFDocument,
    line: string,
    options: Record<string, unknown> = {},
  ) {
    const segments = this.parseInline(line);

    if (segments.length === 0) {
      doc.font('Helvetica').fontSize(12).fillColor('#111111').text(' ', options);
      return;
    }

    segments.forEach((segment, index) => {
      const isLast = index === segments.length - 1;

      const font = segment.code
        ? 'Courier'
        : segment.bold && segment.italic
        ? 'Helvetica-BoldOblique'
        : segment.bold
        ? 'Helvetica-Bold'
        : segment.italic
        ? 'Helvetica-Oblique'
        : 'Helvetica';

      doc
        .font(font)
        .fontSize(segment.code ? 10 : 12)
        .fillColor(segment.code ? '#444444' : '#111111')
        .text(segment.text, { ...options, continued: !isLast });
    });
  }

  // ── Inline markdown parser ────────────────────────────────────────────────

  private parseInline(text: string): TextSegment[] {
    const segments: TextSegment[] = [];
    // Order matters: longer patterns first
    const pattern =
      /(\*\*\*[\s\S]+?\*\*\*|___[\s\S]+?___|`[^`]+`|\*\*[\s\S]+?\*\*|__[\s\S]+?__|\*[\s\S]+?\*|_[\s\S]+?_)/g;

    let lastIndex = 0;
    let match: RegExpExecArray | null;

    while ((match = pattern.exec(text)) !== null) {
      if (match.index > lastIndex) {
        segments.push({
          text: text.slice(lastIndex, match.index),
          bold: false,
          italic: false,
          code: false,
        });
      }

      const raw = match[0];

      if (raw.startsWith('***') || raw.startsWith('___')) {
        segments.push({ text: raw.slice(3, -3), bold: true, italic: true, code: false });
      } else if (raw.startsWith('**') || raw.startsWith('__')) {
        segments.push({ text: raw.slice(2, -2), bold: true, italic: false, code: false });
      } else if (raw.startsWith('`')) {
        segments.push({ text: raw.slice(1, -1), bold: false, italic: false, code: true });
      } else if (raw.startsWith('*') || raw.startsWith('_')) {
        segments.push({ text: raw.slice(1, -1), bold: false, italic: true, code: false });
      }

      lastIndex = match.index + raw.length;
    }

    if (lastIndex < text.length) {
      segments.push({
        text: text.slice(lastIndex),
        bold: false,
        italic: false,
        code: false,
      });
    }

    return segments.filter((s) => s.text.length > 0);
  }
}

